AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Enabled: false

Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false
