dev: &dev
  bucket: arn:aws:s3:us-east-1:229053409903:accesspoint/norwicz
  filename: tmp/reit_data.json

prd: &prd
  bucket: arn:aws:s3:us-east-1:229053409903:accesspoint/norwicz
  filename: data/reit_data.json
