version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build_and_test:
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: gem install bundler
      - run: bundle install
      - run: mkdir tmp
      - run: rake
  run_update:
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"
      - run: gem install bundler
      - run: ./get_financials

workflows:
  pull_request:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master
  update:
    jobs:
      - run_update
    triggers:
      - schedule:
          cron: "0 0 1,6,11,16,21,26 * *"
          filters:
            branches:
              only: master
